// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79sGcSGEWaz8MJOVVmH0BLXGn_vplC9U',
    appId: '1:384286510916:web:f808336d21a3d539549111',
    messagingSenderId: '384286510916',
    projectId: 'flutter-mini-project-1',
    authDomain: 'flutter-mini-project-1.firebaseapp.com',
    storageBucket: 'flutter-mini-project-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeCWPX0s1awP2plzj8WxfFvooaFw9xb38',
    appId: '1:384286510916:android:a2bacff45f00b921549111',
    messagingSenderId: '384286510916',
    projectId: 'flutter-mini-project-1',
    storageBucket: 'flutter-mini-project-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp71Ssbd_j3CzHmB7kVDXDYzk-n_fG5HQ',
    appId: '1:384286510916:ios:1b1a4481c3c99d4a549111',
    messagingSenderId: '384286510916',
    projectId: 'flutter-mini-project-1',
    storageBucket: 'flutter-mini-project-1.appspot.com',
    iosClientId: '384286510916-bjkrpoh2v9j7olee51uiupren1n6hdrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMiniProject1',
  );
}
